### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by guoqi-code** [Sense-GVT/Fast-BEV#13]
when train utils epoch 8,  an error occurs:
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [1488,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.

**Comment by ymlab** [comment]
Unfortunately, this is a training instability problem that has plagued us for a long time, and we currently have no good way to avoid this error. Some feasible methods in practice are to restart the training after resume, or restart the training after adjusting the learning rate.

**Comment by ymlab** [comment]
Any suggestions for solving this issue are welcome.

**Comment by pengcheng001** [comment]
I have encountered similar problems when training other models. There is a high probability that there are illegal data less than 0 in the gt value. For example, the width and height of bbox are less than 0. It is very likely that when doing data aug, the appropriate gt filter out.

**Comment by justttry** [comment]
> I have encountered similar problems when training other models. There is a high probability that there are illegal data less than 0 in the gt value. For example, the width and height of bbox are less than 0. It is very likely that when doing data aug, the appropriate gt filter out.

Did you fix this bug? Any suggestion?

**Comment by Mandylove1993** [comment]
> when train utils epoch 8, an error occurs: /opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/Loss.cu:115: operator(): block: [1488,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.

Are you using distributed training？

**Comment by huichen98** [comment]
我取出数据集前1000帧，打开或者关闭增强，训练都没有报错，但是用作者提供的整个数据集训练，就会出现错误

**Comment by huichen98** [comment]
config -->  fp16 = dict(loss_scale="dynamic")

**Comment by thfylsty** [comment]
关闭Resnet18的torch vision 权重加载，极大的概率减小训崩的情况。

**Comment by WxlSky** [comment]
`
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [1670,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "tools/train.py", line 279, in <module>
    main()
  File "tools/train.py", line 268, in main

`
I have tested all the solutions above, but the problem still exists. any other solutions  ?

**Comment by HaoZhang16613** [comment]
Anyone solved this problem?

**Comment by kokun66** [comment]
i encountered the same issue, is it solved?

**Comment by kokun66** [comment]
this should be a good fix:
free_anchor3d_head.py L131:
change: 
dim=1, keepdim=True).values.clamp(min=t1 + 1e-12)
to:
dim=1, keepdim=True).values.clamp(min=t1 + 1e-6)

**Comment by athrunsunny** [comment]
Maybe your can add torch.nan_to_num() in positive_bad_loos() and negative_bag_loss() 
###################
bag_prob = torch.nan_to_num(bag_prob) 
bag_prob = bag_prob.clamp(0, 1)
###################
prob = torch.nan_to_num(prob) 
prob = bag_prob.clamp(0, 1)
