### ISSUE TITLE
运行pip install -v -e .命令报错

### ISSUE THREAD

**Issue by jinjunxin** [Sense-GVT/Fast-BEV#55]
compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
        subprocess.run(
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/jjx/PycharmProjects/FastBEV/Fast-BEV/setup.py", line 192, in <module>
        setup(
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
        build_ext.build_extensions(self)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
        self._build_extensions_serial()
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
        objects = self.compiler.compile(
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/jjx/anaconda3/envs/FastBEV/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/jjx/anaconda3/envs/FastBEV/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/jjx/PycharmProjects/FastBEV/Fast-BEV/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/jjx/PycharmProjects/FastBEV/Fast-BEV/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Kayxubo** [comment]
Me too.How to solve it？

**Comment by welder-M** [comment]
Me too.How to solve it？

**Comment by BubbleCheese** [comment]
Me too.How to solve it？

**Comment by BubbleCheese** [comment]
> Me too.How to solve it？

Did you solved it?
