### ISSUE TITLE
KeyError: 'FastBEV is not in the models registry'

### ISSUE THREAD

**Issue by Lotusboat** [Sense-GVT/Fast-BEV#87]
I installed mmcv1.4.0, mmdet 2.14.0, mmdet3d0.16.0 and successfully build the project. But when I run train.py it failed: 

> 2024-07-29 15:25:18,850 - mmdet - INFO - Set random seed to 0, deterministic: False
> Traceback (most recent call last):
>   File "tools/train.py", line 283, in <module>
>     main()
>   File "tools/train.py", line 218, in main
>     model = build_model(
>   File "/home/usr/Fast-BEV-dev/mmdet3d/models/builder.py", line 83, in build_model
>     return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
>   File "/home/usr/Fast-BEV-dev/mmdet3d/models/builder.py", line 56, in build_detector
>     return DETECTORS.build(
>   File "/home/usr/Fast-BEV-dev/mmcv1.4.0/mmcv/utils/registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/home/usr/Fast-BEV-dev/mmcv1.4.0/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/home/usr/Fast-BEV-dev/mmcv1.4.0/mmcv/utils/registry.py", line 44, in build_from_cfg
>     raise KeyError(
> **KeyError: 'FastBEV is not in the models registry'**

I uninstalled and installed the dependencies but it didn't help. Can you help me implement it?

**Comment by najwabelarbi2** [comment]
any update on this?

**Comment by venkataramanas1** [comment]
Have you up the project ? can you provide me steps to build and run properly ?
