### ISSUE TITLE
Document on how to run eval, test and train, failed by reading the code

### ISSUE THREAD

**Issue by weiyshay** [Sense-GVT/Fast-BEV#93]
Hi,
Thank you very much for the project!

I am trying to set the env to run eval, test and training if possible, after setting the environment, I got errors when running the test. Anywhere or doc that i can check on the command line and the expected result? 

My test errors:
eval:
```
 python3 tools/eval.py  configs/fastbev/exp/paper/fastbev_m0_r18_s256x704_v200x200x4_c192_d2_f4.py --out data/nuscenes/nuscenes_infos_val.pkl --show --eval bbox --show-dir=data
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.471 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
lane thickness: 2
lane thickness: 2
lane thickness: 2
lane thickness: 2
lane thickness: 2
 
loading results from data/nuscenes/nuscenes_infos_val.pkl
Traceback (most recent call last):
  File "tools/eval.py", line 217, in <module>
    main()
  File "tools/eval.py", line 213, in main
    print(dataset.evaluate(outputs, vis_mode=args.vis, **eval_kwargs))
  File "Fast-BEV/mmdet3d/datasets/nuscenes_monocular_dataset_map_2.py", line 207, in evaluate
    eval_seg = 'bev_seg' in results[0]
KeyError: 0
```

Test:
```
python3 ./tools/test.py configs/fastbev/exp/paper/fastbev_m0_r18_s256x704_v200x200x4_c192_d2_f4.py data/pretrained_models/cascade_mask_rcnn_r18_fpn_coco-mstrain_3x_20e_nuim_bbox_mAP_0.5110_segm_mAP_0.4070.pth --eval bbox

Traceback (most recent call last):
  File "/root/anaconda3/envs/fastbev-py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/fastbev-py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/fastbev-py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/Fast-BEV/mmdet3d/datasets/nuscenes_monocular_dataset_map_2.py", line 55, in __getitem__
    return self.prepare_test_data(idx)
  File "/data/Fast-BEV/mmdet3d/datasets/custom_3d.py", line 174, in prepare_test_data
    example = self.pipeline(input_dict)
  File "/data/Fast-BEV/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/data/Fast-BEV/mmdet3d/datasets/pipelines/multi_view.py", line 38, in __call__
    _results = self.transforms(_results)
  File "/data/mFast-BEV/mdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/data/Fast-BEV/mmdetection/mmdet/datasets/pipelines/loading.py", line 51, in __call__
    self.file_client = mmcv.FileClient(**self.file_client_args)
  File "/data/mmcv/mmcv/fileio/file_client.py", line 814, in __new__
    _instance.client = cls._backends[backend](**kwargs)
  File "/data/mmcv/mmcv/fileio/file_client.py", line 114, in __init__
    raise ImportError('Please install petrel_client to enable '
ImportError: Please install petrel_client to enable PetrelBackend
```

**Comment by ymlab** [comment]
I will release a new version of fastbev++ code in the near future, based on the standard setting of bevdet, so stay tuned.
Some new features:
 - support for fusion of depth information;
 - no need for custom operators, completely based on onnx native operators, so that onemodel + cross-platform deployment can be achieved.

**Comment by weiyshay** [comment]
Nice! Definitely happy to know! 

When is the project to be released?

**Comment by venkataramanas1** [comment]
Have you up the project ? can you provide me steps to build and run properly ?
